### ISSUE TITLE
What about Prometheus?

### ISSUE THREAD

**Issue by juanyque** [crazy-canux/awesome-monitoring#2]
Hi, recently I have read about Prometheus (plus Grafana).

I'm testing it. It seems nice. Perhaps you have interest in add to your great list.

Thanks for your work!

**Comment by crazy-canux** [comment]
Hi,
       Thanks for your information.
        Can you help create a PR?

**Comment by crazy-canux** [comment]
Considering I don't know anything about Prometheus.
And there is no PR for this.
I close thie issue first.
